spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crud
    username: root
    password: admin


  jpa:
    hibernate:
      ddl-auto: none

    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

server:
  servlet:
    context-path: /users